### ISSUE TITLE
Can't find DataModel stores

### ISSUE THREAD

**Issue by MrVoltz** [RileyGuy/CherryPick#8]
Hi, let me firstly thank you for this great mod. I've found an issue with the ProtoFlux Node browser that certain nodes can't be found, for example `DataModelValueFieldStore<T>`.

![Resonite 11 11 2023 21_57_11](https://github.com/RileyGuy/CherryPick/assets/5212649/bf9a7e9a-8574-4c03-b8db-160677d83e2e)
![Resonite 11 11 2023 21_57_41](https://github.com/RileyGuy/CherryPick/assets/5212649/c11eb684-97ae-4461-b43b-5c2a2c7a504d)

**Comment by RileyGuy** [comment]
What version of ResoniteModLoader are you using, and what version of CherryPick are you using? I've checked this and can't replicate it on my side. Both the component and protoflux browsers show the data model stores just fine.

![image](https://github.com/RileyGuy/CherryPick/assets/9770110/6c57d908-929e-4671-ad4c-3ff9323708e5)

**Comment by Nytra** [comment]
I have tried searching for `DataModel` and found that some don't appear in the ProtoFlux browser but do appear in the regular component selector. I think this is because there are actuaally two components called `DataModelValueFieldStore<T>`, one of them exists in `ProtoFlux/Runtimes/Execution/Nodes/Variables` and the other exists in `Uncategorized`.

![2023-11-13 01 09 04](https://github.com/RileyGuy/CherryPick/assets/14206961/3f124ad4-0922-461f-be3d-c0527b3ab3b7)

**Comment by MrVoltz** [comment]
OnEngineInit is called right after ResoniteModLoader.dll is loaded. Because the Flux nodes are spread in multiple dlls, the node list CherryPick sees depends on the dll load order. I don't know why is it different on my machine, I have a lot of other mods and some additional libs installed. Delaying the initialization fixes the issue, but maybe I'll update the PR to move the scanning to its own method from the static block, because this is still a little bit janky.
Martin

13. listopadu 2023 2:17:28 SEČ, Nytra ***@***.***> napsal:

**Comment by RileyGuy** [comment]
This evidently does not appear to fix the problem, looking into other solutions.

**Comment by RileyGuy** [comment]
Fixed in [f3d753a](https://github.com/RileyGuy/CherryPick/commit/f3d753a42d26e245be33a0792827c1df2ce636ef)
